/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";

// The model is meshopt-quantized, so the scale/offset that restores the
// original geometry lives on the glTF nodes and must be applied to the meshes.
const nodeTransform = ({ position, quaternion, scale }) => ({
  position,
  quaternion,
  scale,
});

export function Planet(props) {
  const shapeContainer = useRef(null);
  const shperesContainer = useRef(null);
  const ringContainer = useRef(null);
  const { nodes, materials } = useGLTF("/models/Planet.glb");

  useGSAP(() => {
    const tl = gsap.timeline();
    tl.from(shapeContainer.current.position, {
      y: 5,
      duration: 3,
      ease: "circ.out",
    });
    tl.from(
      shperesContainer.current.rotation,
      {
        x: 0,
        y: Math.PI,
        z: -Math.PI,
        duration: 10,
        ease: "power1.inOut",
      },
      "-=25%"
    );
    tl.from(
      ringContainer.current.rotation,
      {
        x: 0.8,
        y: 0,
        z: 0,
        duration: 10,
        ease: "power1.inOut",
      },
      "<"
    );
  }, []);

  return (
    <group ref={shapeContainer} {...props} dispose={null}>
      <group ref={shperesContainer}>
        <mesh
          geometry={nodes.Sphere.geometry}
          material={materials["Material.002"]}
          {...nodeTransform(nodes.Sphere)}
        />
        <mesh
          geometry={nodes.Sphere2.geometry}
          material={materials["Material.001"]}
          {...nodeTransform(nodes.Sphere2)}
        />
      </group>
      <mesh
        ref={ringContainer}
        geometry={nodes.Ring.geometry}
        material={materials["Material.001"]}
        {...nodeTransform(nodes.Ring)}
      />
    </group>
  );
}

useGLTF.preload("/models/Planet.glb");
